docs(cli): added new documentation for Ignite CLI
infinitered/ignite pull request #2294
Opened 2022-11-09 16:22 UTC by frankcalise

## Describe your PR
- Closes #2291
- Initial go at documenting the power behind the CLI!

![image](https://user-images.githubusercontent.com/374022/200884275-14b7929f-7238-4ad7-ac64-d482c780946e.png)

2022-11-09 17:19 UTC, joshuayoes requested changes
I've got some nitpicky grammar suggestions and an edit of the cache command section. But otherwise, this looks great! This will be really useful for Ignite users.

2022-11-09 17:19 UTC, joshuayoes commented on docs/Ignite-CLI.md
> +Generally speaking, you shouldn't have to use this command. However, it is helpful for managing the dependency cache Ignite uses when spinning up new projects. You can opt out of using the cache, see
This to me suggests that the cache is used by default, which it is not. I have some suggestions on a replacement here

```suggestion
The [`new` command](#new) has a `useCache` flag that allows you to cache your dependencies to speed up future uses of `new`. By default, this flag is `false`. This command is provided to allow for interacting with the dependency cache file folder.

#### Subcommands
- `npx ignite-cli cache help` outputs help command to describe cache subcommands
- `npx ignite-cli cache path` outputs the path of the cache folder on your system 
- `npx ignite-cli cache clear` deletes the cache folder on your system
```

2022-11-09 17:19 UTC, joshuayoes commented on docs/Ignite-CLI.md
> +- `npx ignite-cli cache`
```suggestion
- `npx ignite-cli cache`
- alias `npx ignite-cli c`
```

2022-11-09 17:19 UTC, joshuayoes commented on docs/Ignite-CLI.md
> +Provides this list of commands and a small description of each in your terminal.
```suggestion
Provides this list of commands and a small description of each command in your terminal.
```

2022-11-09 17:19 UTC, joshuayoes commented on docs/Ignite-CLI.md
> +Fires up a new issue on GitHub.com prefilled with collected [doctor](#doctor) information. Simply describe your steps to help reproduce the issue (and provide any relevant code snippets or repository
```suggestion
Fires up a [new issue for Ignite on GitHub](https://github.com/infinitered/ignite/issues/new/) prefilled with collected [doctor](#doctor) information. Simply describe your steps to help reproduce the issue (and provide any relevant code snippets or repository) and press submit!
```

2022-11-09 17:24 UTC, frankcalise commented
> I've got some nitpicky grammar suggestions and an edit of the cache command section. But otherwise, this looks great! This will be really useful for Ignite users.

Thanks appreciate it!

2022-11-09 17:28 UTC, jamonholmgren approved these changes
This is :100: excellent work

2022-11-09 18:53 UTC, merged

2022-11-10 03:45 UTC, infinitered-circleci commented
:tada: This PR is included in version 8.3.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ignite-cli/v/8.3.1)
- [GitHub release](https://github.com/infinitered/ignite/releases/tag/v8.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: