chore: enable eslint react-hook/recommended rule set
infinitered/ignite pull request #2454
Opened 2023-05-31 04:29 UTC by guiccbr

## Please verify the following:

- [ ] `yarn test` **jest** tests pass with new tests, if relevant
- [ ] `README.md` has been updated with your changes, if relevant

## Describe your PR

Enable eslint react-hook/recommended rule set, as recommended in the react dev website: https://react.dev/learn/editor-setup#linting

Related discussion: https://github.com/infinitered/ignite/discussions/2453

2023-05-31 04:31 UTC, guiccbr commented on src/commands/new.ts
> +/* eslint-disable react-hooks/rules-of-hooks */
This file has a method that starts with `use*` and react-hooks/rules-of-hooks is complaining about that.

I'm not sure if this is the best approach here.

2023-06-07 00:31 UTC, joshuayoes requested changes
Made some comments to move some of the linting settings, but otherwise looks good so far

2023-06-07 00:31 UTC, joshuayoes commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
Can you move this package to [boilerplate/package.json](https://github.com/infinitered/ignite/blob/master/boilerplate/package.json) instead? 

This top level package.json is for the cli, where as the `boilerplate` folder is for the app content.

2023-06-07 00:31 UTC, joshuayoes commented on package.json
> +      "plugin:react-hooks/recommended"
Can you move this package to [boilerplate/package.json](https://github.com/infinitered/ignite/blob/master/boilerplate/package.json) instead?

This top level package.json is for the cli, where as the boilerplate folder is for the app content.

2023-06-28 03:33 UTC, guiccbr commented
Thanks. I'll close and reopen because after enabling the the linter failed for the generated app. I'll need some more time to fix that.

2023-06-28 03:33 UTC, closed without merging