fix(boilerplate): jest.config.js remove jsdom test env
infinitered/ignite pull request #2632
Opened 2024-02-11 04:24 UTC by frankcalise

## Please verify the following:

- [ ] `yarn test` **jest** tests pass with new tests, if relevant
- [ ] `yarn lint` **eslint** checks pass with new code, if relevant
- [ ] `yarn format:check` **prettier** checks pass with new code, if relevant
- [ ] `README.md` (or relevant documentation) has been updated with your changes

## Describe your PR
- Closes #2605
- Better RNTL support out of box
- testEnvironment `jsdom` should only be used for web (which although we support, isn't our main target)

2024-02-13 20:25 UTC, markrickert requested changes
@frankcalise I also just ran into this issue, but to fix it i had to remove the same property from the base `package.json` as well: https://github.com/infinitered/ignite/blob/master/package.json#L154

2024-02-13 20:27 UTC, frankcalise commented
@markrickert that was a result of running `yarn test` from the root project dir that you hit this error?

2024-02-13 20:29 UTC, markrickert commented
@frankcalise Sorry, false alarm... i'm getting a different error actually:

```
 FAIL  src/tools/demo.test.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

      at new NodeEnvironment (node_modules/jest-environment-node/build/index.js:88:49)

Test Suites: 6 failed, 6 total
```

Though it's probably something i did in my branch.

2024-02-21 16:53 UTC, markrickert approved these changes

2024-02-21 16:56 UTC, merged

2024-02-21 17:01 UTC, infinitered-circleci commented
:tada: This PR is included in version 9.6.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ignite-cli/v/9.6.1)
- [GitHub release](https://github.com/infinitered/ignite/releases/tag/v9.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: