Add support for custom headers in AutoImage
infinitered/ignite pull request #2767
Opened 2024-09-07 15:16 UTC by LeXuanKhanh

## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `yarn lint` **eslint** checks pass with new code, if relevant
- [x] `yarn format:check` **prettier** checks pass with new code, if relevant
- [x] `README.md` (or relevant documentation) has been updated with your changes

## Describe your PR
As the title, my project is currently using your boilerplate but AutoImage component is missing the feature, it would be great if the main repo supported it

2024-10-16 13:16 UTC, frankcalise requested changes
Thanks for this, left one comment.

Also, could you look into updating the documentation to match this change in https://github.com/infinitered/ignite/blob/master/docs/boilerplate/app/components/AutoImage.md?

2024-10-16 13:16 UTC, frankcalise commented on boilerplate/app/components/AutoImage.tsx
> +  }
Could you please document this to be consistent with the other props? Something mentioning that these are the headers for the request

2024-10-17 18:31 UTC, LeXuanKhanh commented
> Thanks for this, left one comment.
> 
> Also, could you look into updating the documentation to match this change in https://github.com/infinitered/ignite/blob/master/docs/boilerplate/app/components/AutoImage.md?

I have updated the document, please check it., thanks

2024-11-20 15:42 UTC, LeXuanKhanh commented
hi @frankcalise, any comment or response about my PR ? thanks

2024-12-07 23:08 UTC, frankcalise approved these changes
Thanks, sorry I've been busy. Appreciate you checking up on it!

2024-12-07 23:16 UTC, merged

2024-12-10 22:44 UTC, infinitered-circleci commented
:tada: This PR is included in version 10.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ignite-cli/v/10.1.0)
- [GitHub release](https://github.com/infinitered/ignite/releases/tag/v10.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: