refactor: replace shell commands with filesystem API
infinitered/ignite pull request #2817
Opened 2024-10-19 10:33 UTC by AsterisMono

## Please verify the following:

- [ ] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `yarn lint` **eslint** checks pass with new code, if relevant
- [x] `yarn format:check` **prettier** checks pass with new code, if relevant
- [ ] `README.md` (or relevant documentation) has been updated with your changes
- [ ] If this affects functionality there aren't tests for, I manually tested it, including by generating a new app locally if needed ([see docs](https://docs.infinite.red/ignite-cli/contributing/Contributing-To-Ignite/#testing-changes-from-your-local-copy-of-ignite)).

## Describe your PR

Fixes #2816.

This PR replaces the `rm` and `mv` shell commands in project creation with `gluegun (fs-jetpack)` filesystem calls to ensure compatibility with Windows (Since there's no `mv` and `rm` in Windows CMD).

2024-10-22 05:44 UTC, frankcalise commented
Thanks for this! We will try and get it tested soon

2024-10-29 19:06 UTC, joshuayoes requested changes
~~I did some testing but I realized I was testing on the wrong branch, disregard this review.~~

2024-10-29 19:06 UTC, joshuayoes commented on src/tools/react-native.ts
> +export function cleanupExpoRouterConversion(toolbox: GluegunToolbox, targetPath: string) {
I think this section still needs some work, I'm getting a failure when I run the Expo Router workflow

```
npx ignite-cli new ExpoRouterApp \
        --bundle=com.exporouterapp \
        --git \
        --install-deps=false \
        --packager=npm \
        --target-path=C:\Users\joshu\Code\ExpoRouterApp \
        --remove-demo=false \
        --experimental=expo-router \
        --workflow=CNG \
        --no-timeout=false \
        --state=mst
```

When I try to run any expo commands, I get

```
CommandError: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- C:\Users\joshu\Code\ExpoRouterApp\node_modules\ajv-keywords\dist\definitions\typeof.js
```

2024-10-29 19:06 UTC, joshuayoes commented on src/tools/react-native.ts
> +  workingDir.cwd("src").remove("app.tsx")
It seems that commands aren't quite working on my Windows machines, I'm stilling getting `src/app.tsx` and some of the like:
![image](https://github.com/user-attachments/assets/faa3b5d2-8689-41dd-9398-91092a62fb72)

2024-10-29 19:12 UTC, joshuayoes reviewed
I was able to reproduce the issue with the Expo Router flow on Windows

2024-10-29 19:32 UTC, joshuayoes approved these changes
Gave this a test, the Expo Router workflow works on Windows ✅

2024-10-29 21:44 UTC, frankcalise approved these changes
Thank you!

2024-10-29 21:45 UTC, merged

2024-10-29 21:59 UTC, infinitered-circleci commented
:tada: This PR is included in version 10.0.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ignite-cli/v/10.0.2)
- [GitHub release](https://github.com/infinitered/ignite/releases/tag/v10.0.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: